name: Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  push_docker:
    name: Push Docker Image
    runs-on: ubuntu-22.04
    timeout-minutes: 720
    strategy:
      matrix:
        rosdistro: [humble]
        arch: [arm64]
        # Build test for arm64 CPU is broken.
        # This is a temporary solution and will be repaired in the future.
        # See also https://github.com/tier4/scenario_simulator_v2/pull/1295
        # arch: [amd64, arm64]
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false

      - name: Install docker for ubuntu runner
        uses: docker/setup-buildx-action@v3

      - name: Install QEMU
        uses: docker/setup-qemu-action@v3

      - uses: actions/checkout@v4

      - name: Build (${{ matrix.arch }})
        if: github.event_name == 'pull_request'
        uses: docker/bake-action@v3
        with:
          files: |
            ./docker-bake.hcl
          workdir: .
          set: |
            *.cache-to=type=gha,mode=max
            *.cache-from=type=gha
          push: false
          targets: |
            ${{ matrix.rosdistro }}_base_${{ matrix.arch }}
